colombo=[
"Hilton+Colombo",
"Cinnamon+Grand+Colombo",
"The+Kingsbury",
"Cinnamon+Lakeside+Colombo",
"Casa+Colombo+Hotel",
"Majestic+Cinema",
"Savoy+3D+Cinema",
"Regal+Cinema",
"Cine+City",
"Viharamahadevi+Park",
"Savoy+3D+Cinema",
"Gangaramaya+Park",
"National+Museum",
"Dutch+Museum",
"Sri+Lanka+Air+Force+Museum",
"Gangaramaya+Temple",
"Dehiwala+Zoo",
"Bally's+Casino",
"Pettah+Floating+Market",
"Shri+Ponnambalawaneswaram+Kovil",
"Wolvendaal+Church",
"National+Art+Gallery",
"Galle+Face+Beach",
"Colombo+Lighthouse",
"Kelaniya+Raja+Maha+Vihara",
"Dutch+Hospital+Shopping+Precinct",
"Colombo+Public+Library",
"Premadasa+International+Cricket+Stadium",
"Excel+World+Entertainment+Park",
"Galle+Face+Hotel",
"Ratmalana+Airport",
"LeisureWorld+Water+Park",
"Guruge+Park",
"Kiddies+Pool+Slides",
"Cafe+Mocha+by+Barista",
"Chinese+Dragon+Cafe+Bambalapitiya",
"Cup+Cafe",
"The+Commons+Coffeehouse",
"Arcade+Independence+Square",
"The+Fab",
"Liberty+Plaza",
"Colombo+City+Centre",
"Sugathadasa+Stadium",
"The+Cricket+Club+Cafe",
"Diyatha+Uyana+Aquarium",
"Water+World+Lanka",
"North+West+Aquarium",
"Lionel+Wendt+Art+Gallery",
"Jana+Kala+Kendraya"
]

galle = [
"Galle+Fort",
"National+Maritime+Museum",
"National+Museum+of+Galle",
"Galle+Lighthouse",
"Historical+Mansion+Museum",
"All+Saints'+Church,+Galle",
"Galle+Harbour",
"Galle+Dutch+Fort",
"Christian+Reformed+Church",
"St.+Mary's+Cathedral,+Galle",
"Dutch+Mansion+Museum",
"Beach+of+Bonavista",
"Galle+Library",
"Gall+Fort+Clock+Tower",
"Stelzenfischer+auf+Sri+Lanka",
"Queen's+Cinema",
"Old+Dutch+Hospital",
"Carrousel+De+Galle",
"Cinnamon+Island",
"Beach+Park+-+Galle+Municipal+Council",
"Mahamodara+Beach+Park+&+Marine+Walk",
"King+Fisher+River+Safari",
"Koggala+Beach+Park",
"Royal+Dutch+Cafe",
"Serendipity+Arts+Cafe",
"Galle+Fort+Hotel",
"Tamarind+Hill",
"Jetwing+Kurulubedda",
"Galle+International+Cricket+Stadium",
"Water+Hole",
"Japanese+Peace+Pagoda",
"Gangarama+Purana+Viharaya",
"Fort+Meeran+Jumma+Masjid",
"Koggala+Air+Force+Base",
"Tsunami+Museum",
"Turtle+Museum",
"Martin+Wickramasinghe+House",
"Jungle+Beach",
"Sithuvili+Gallery",
"The+Cell+Art+Gallery",
"Sail+Lanka+Charter+Bentota",
"Jetwing+Lighthouse",
"Avenra+Beach+Hotel",
"New+Old+Dutch+House",
"Unawatuna+Beach+Resort",
"Lucky+Fort+Restaurant",
"The+Stairway",
"Lucky+Tuna",
"Thaproban+Beach+House",
"Jungle+Beach+Disko"
]

kandy = [
"Temple+of+the+Tooth",
"Kandy+Lake",
"Udawatta+Kele+Sanctuary",
"Sigiriya",
"Sri+Dalada+Maligawa",
"Botanical+Gardens+Peradeniya",
"Dambulla+cave+temple",
"Knuckles+Mountain+Range",
"Royal+Bar+Hotel",
"Wales+Park",
"Highway+museum+complex+Kiribathkumbura",
"Natha+Devale+Kandy",
"Media+Special+Project+Bureau",
"International+Buddhist+Museum",
"Sri+Rajopawanaramaya+Temple",
"Tusker+Raja+Museum",
"Bahiravokanda+Vihara+Buddha+Statue",
"Slightly+Chilled+Lounge+Bar+and+Restaurant",
"Asgiriya+International+Cricket+Stadium",
"Pallekale+International+Cricket+Stadium",
"Nittawela+Rugby+Stadium",
"Lion+Park+Trinity+College+Rugby+Stadium",
"Hantane+Shadow+Retreat+Spa",
"Wedda+peni+ella",
"Kandy+Baptist+Church",
"Udawatta+Kele+Sanctuary",
"New+Ranweli+Spice+Garden+Kandy",
"Huluganga+Ella+Waterfall",
"Victoria+Reservoir",
"Devon+Falls",
"The+Empire+Cafe",
"Devon+Food+Court",
"Hotel+Kandyan+Arts+Residency",
"KCC",
"Municipal+Public+Shopping+Complex",
"Hotel+Hill+Top+",
"Mahaweli+Reach+Hotel",
"The+Grand+Kandyan+Hotel",
"Hotel+Suisse",
"Regal+Cinema",
"Wembley+Theater",
"Sri+Sambuddhaloka+Samadhi+Temple,+Kandy",
"Wattarantenna+Purana+Gal+Len+Viharaya",
"Vishnu+Devalaya-kandy",
"Asgiri+Maha+Viharaya",
"Pinnawala+Zoo",
"Ranvilla+wild+cabin+in+paradise+jungle+mist",
"Queen's+Hotel",
"Wedamedura+Ayurveda"
]

eliya = [
"Hakgala+Botanical+Garden",
"Devon+Falls",
"St.+Clairs+Falls",
"Pidurutalagala",
"Galway's+Land+National+Park",
"Horton+Plains+National+Park",
"Adam's+Peak",
"Seetha+Amman+Temple",
"Aberdeen+Falls",
"Victoria+Park+Nuwara+Eliya",
"Lover's+leap+Waterfall",
"Pedro+Tea+Factory",
"Moon+Plains",
"Victoria+Museum",
"Mackwoods+Museum",
"Suwamadu+Ayurvedic+Health+Resort",
"Araliya+Green+Hills+Hotel",
"Alpine+Hotel",
"Heritance+Tea+Factory",
"Glendower+Hotel",
"Jetwing+St.+Andrews",
"Calamander+Lake+Gregory",
"Lake+View+Comfort+Bungalow",
"The+Tea+Garden",
"Holy+Trinity+Church",
"Kadadora+Raja+Maha+Viharaya",
"Seetha+Amman+Temple",
"Nuwara+Eliya+Race+Course+Ground",
"Grand+Indian",
"Mlesna+Tea+Castle",
"Zesta+Tea+Cup",
"Araliya+Green+Hills+Hotel",
"Samuel+Baker+Restaurant+Windsor+Hotel",
"Nuwara+Eliya+Golf+Club",
"OakRay+Summer+Hill+Breeze+Hotel",
"Lake+View+Pub",
"Restaurant+Two",
"Cool+Feel+Rest",
"Champ+Villa",
"Bomburuella+Waterfall",
"Baker's+Falls",
"Laxapana+Falls",
"Ramboda+Falls",
"Lanka+Ella+Waterfall",
"Queen+Elizabeth+Plaza",
"Nuwara+Eliya+Dedicated+Economic+Center",
"Sanasa+Orex+City",
"Suwamadu+Ayurvedic+Health+Resort",
"Public+Library+Nuwara+Eliya",
"Midky+Hotel"
]

polonnaruwa=[
"Polonnaruwa+Vatadage",
"Parakrama+Samudra",
"Minneriya+National+Park",
"Somawathiya+Chaitya",
"Nissanka+Latha+Mandapaya",
"Lankatilaka+Vihara",
"Kiri+Vehera",
"Hatadage",
"Dalada+Maluva",
"Shiva+Devalaya",
"Alahana+Pirivena",
"Vejayanta+Pasada",
"Archaeological+Museum",
"Atadage",
"Gal+Potha",
"Pothgul+Viharaya",
"Pothgul+Vehera+(Ancient+Library)",
"Bathing+Pool+(Kumara+pokuna+)",
"Maha+Parakkramabahu+Statue",
"Pabalu+Wehera",
"The+Old+Palace+of+King+Parakramabahu",
"Baddha+Seema+Malakaya",
"Council+Chamber",
"Polannaruwa+historical+place",
"Ancient+Bhikku+Hospital+(Hospital+For+Buddhist+Monks)",
"Seyara+holiday+resort",
"The+Lake+Hotel",
"Hotel+Sudu+Araliya",
"The+Lake+House",
"The+Heritage+Polonnaruwa",
"Royal+College+Stadium",
"Flood+Plains+National+Park",
"Angammedilla+National+Park",
"Kadawalawewa+Tank",
"Ariya+Rest+House",
"Thidas+Arana+Restaurant",
"The+Senaro+Holiday+Inn",
"Polonnaruwa+Holiday+Inn",
"Palm+Garden+Tourist+Guest+House",
"Thuparama+Image+House"
]

kataragama = [
"Kataragama+Temple",
"Kiri+Vehera",
"Heliport+of+Kataragama",
"Hotel+Okrin",
"Mandara+Rosen+Kataragama+Hotel",
"Hotel+Sunflower",
"Katharagama+Safari+Hotel",
"Big+Game+Camp+Yala",
"Katharagama+Sanctuaries",
"Leopard+Trails",
"Camp+Leopard+Yala+Safari+Glamping",
"Ruhunu+Maha+Kataragama+Devalaya",
"Gem+River+Edge",
"Mahasen+Devalaya",
"Sella+Kataragama+Lord+Ganesh+Temple",
"sthya+sri+kele+ganapathi+kovil+sithulpawwa+RD+kataragama",
"Kebiliththa+Dewalaya",
"Lakshmi+Devalaya",
"Sri+Dharmanikethanaya+Temple",
"Maha+Sakvithi+Rawana+Statue",
"Heina+Nature+Resort+&+Yala+Safari",
"Detagamuwa+Wewa",
"Grand+Tamarind+Lake+Kataragama",
"Archaeological+Museum",
"Kataragama+Kauthukagaraya",
"Ranjith+Madduma+Bandara+Stadium",
"Janith+Night+Club",
"Ridiyagama+Safari+Park"
]

trinco = [
"Sri+Pathrakali+Temple",
"Fort+Frederick",
"Koneswaram+Kovil+Temple",
"Lovers+Leap",
"Marble+Beach+Airforce+Resort",
"Trinco+Blu+by+Cinnamon",
"The+Residence+Nilaveli",
"Jungle+Beach+Resort",
"Kandaswamy+Temple",
"Sail+Lanka+Charter+-+Trincomalee",
"Naval+And+Maritime+Museum",
"Hoods+Tower+Naval+Museum",
"Protected+Archaeological+Monunent",
"Commonwealth+WAR+Cemetery",
"Orr's+hill+army+museum",
"Trinco+Beach+Hotel",
"Pigeon+Island+Beach+Hotel",
"Hotel+Silver+Beach",
"Trincomalee+Airport",
"MPCS+Shopping+Complex",
"Sri+Pathrakali+Temple",
"CPM+Trincomalee",
"Dockyard+Methodist+Church",
"Chinabay+Temple",
"Mutraveli+Appa+Shrine+&+Thakiya+Masjid",
"Mc+Heyzer+Stadium",
"Amaranthe+Bay+Resort+&+Spa",
"Sarasvathi+Cinema",
"Hindu+Cultural+Hall",
"Sellam+Premier+3D+Cinema",
"Andamkulam+Weva",
"Isha+Water+Park",
"Pigeon+Island+National+Park",
"Kanniya+Hot+Water+Well",
"Dutch+Bank+Cafe",
"Cafe'+on+the+18th",
"Green+Park+Hotel",
"Hotel+Blue+Waves",
"Aqua+Hotel+Trincomalee",
"Victoria+Inn"
]

anura = ["Mirisawetiya+Stupa",
"Kuttam+Pokuna,+Twin+Ponds",
"Thuparamaya",
"Ulagalla+Resort",
"Jaya+Sri+Maha+Bodhiya",
"Eth+Pokuna",
"Isurumuniya+Temple",
"Ranmasu+Uyana",
"Lovamahapaya+",
"Nakha+Vihara",
"Mahasena's+Palace",
"Abhayagiri+Museum",
"Archaeological+Museum",
"Folk+Museum",
"Jethawana+Museum",
"Malwathu+Oya+Caravan+Park",
"Queens+Park+Anuradhapura",
"SunRise+Coffee+Shop",
"Mango+Mango+Restaurant",
"Avasta+Resort+and+Spa",
"The+Sanctuary+at+Tissawewa",
"Cinestar+Cinema",
"Willmax+-+Anuradhapura",
"Anuradhapura+Airport",
"Wilpattu+National+Park",
"United+Sports+Club",
"Ruwanwelisaya+",
"Dhammachethiya+Meditation+Monestry",
"Sirisangabo",
"Jamia+Khadija+Jumma+Masjid",
"Pothanegama+Catholic+Church",
"Buddagaya+Viharaya",
"Sri+Bodhirukkharama+Maha+Viharaya",
"Asokaramaya+Pankuliya+Temple",
"Burma+Temple",
"Samadhi+Viharaya",
"Lankarama+Dagaba",
"Anuradhapura+Jummah+Mosque",
"Wijayapura+Dewalaya",
"Hathareswela+Buddhist+Temple",
"Basawakkulama+Tank",
"Thissa+Wewa",
"Abhayavapi",
"Nachchaduwa+Tank",
"Bastian+Pilgrims'+Rest",
"Swasti+Ayurvedic+Treatment+Center+&+Spa",
"Recreation+Club",
"Siththampalam",
"Miridiya+Lake+Resort",
"Platinum+Resort"
]

badulla = [
"Rex+Theatre",
"Indrani+Cinema+and+Restaurant",
"Rukee+Pub",
"Dunhinda+Waterfall",
"Adisham+Bungalow",
"Diyaluma+Falls",
"Ravana+Falls",
"Lanka+Ella+Waterfall",
"Muthiyangana+Raja+Maha+Viharaya",
"Badulla+Jumma+Mosque",
"Lighthouse+Church+-+Badulla",
"St'+Marks+Church+",
"Rambukpotha+Raja+Maha+Viharaya",
"Sri+Paetchi+Amman+Kovil",
"Sri+Bodhirukkarama+Purana+Viharaya",
"Kammanankada+Pansala",
"Thapowana+Dharmayathanaya",
"Rupika's+Cafe",
"Weligama+Holiday+Inn",
"Capitalcity+Hotel+",
"Laura",
"Hotel+Sayonara",
"Prince+Hotel",
"Hotel+Ashford",
"Colling+Wood+Hotel",
"Onel+Kids+Park",
"Chaplon+Tea+Estate+Passara",
"Thangamale+Sanctuary",
"Badulla+Museum",
"Badulla+Swimming+Complex",
"Senarath+Paranavithana+Public+Library",
"Suwamadu+Ayurvedic+Health+Resort",
"98+Acres+Resort+&+Spa",
"5th+Mile+Post+Waterfalls",
"Surathali+Ella",
"Kuda+Dunhinda+Waterfall"
]

matara = [
"Matara+Church",
"Weherahena+Poorwarama+Rajamaha+Viharaya",
"Matara+Bodhiya",
"Dutch+Church",
"Manthinda+Pirivena",
"Uthpalawanna+Sri+Vishnu+Devalaya",
"Star+Fort",
"Matara+Fort",
"Polhena+Reef+Garden+Hotel",
"Amaloh+by+Jetwing",
"Turtle+Eco+Beach",
"Dutch+Star+Fort+-+Matara",
"1950+Souvenir+Shop",
"Madiha+Beach",
"Matara+Beach+Park",
"7th+Wave+Beach+House",
"Polhena+Beach",
"Sea+Turtle+Hatchery",
"Kalukanda+Lake",
"Matara+Shopping+Complex",
"Weherahena+Poorwarama+Rajamaha+Viharaya",
"Samudragiri+Viharaya",
"Bandaramulla+Temple",
"Tenavaram+Temple",
"Sri+Meenadchi+Sundareswarar+Temple",
"Cafe+Amazon+Matara",
"Cafe+4+U",
"The+Dutchman's+Street",
"Reef+Edge",
"Caribbean+Gate",
"Floranze+Restaurant",
"Sky+Lite+3D+Cinema",
"Hotel+Royal+Sea+Wind",
"Sunbeam+Coral+Villa",
"Randuma+Villas",
"Kushtarajagala+Statue",
"Uyanwatta+Stadium",
"Ridiyagama+Safari+Park",
"Sri+Sharavi+Beach+Villas+&+Spa",
"Aroma+Spa+Ayurvedha",
"Divers+Land+Dive+Club",
"Paradise+Diving+Center",
"Banana+Garden",
"Matara+Church"
]


import urllib.request
import json
key = 'AIzaSyBAMiNgTq2xYFbRWN4XR-1sg1e1XfFSpYA'
from pymongo import MongoClient

client = MongoClient('localhost', 27017)
db = client.script

for name in matara:
    name = name.replace(" ","+")
    response = urllib.request.urlopen("https://maps.googleapis.com/maps/api/place/textsearch/json?query=sri+lanka+" + name + "&key=AIzaSyCLeTR2tSokFuII-Mr4BI65K-HNYbiBuN0").read().decode('utf8')
    object = json.loads(response)
    count = 1

    if(len(object['results']) != 0):
        places = object['results']

        for obj in places:
            if (count is 1):
                count += 1

                preprocessed = {}
                preprocessed['id'] = obj['place_id']
                if('vicinity' in obj):
                    areas = obj['vicinity'].split(",")
                    area = areas[len(areas)-1].replace(" ","")
                else:
                    area = "Matara"
                preprocessed['area'] = area
                preprocessed['longitude'] = obj['geometry']['location']['lng']
                preprocessed['latitude'] = obj['geometry']['location']['lat']
                if ('rating' in obj):
                    preprocessed['rating'] = obj['rating']
                preprocessed['name'] = obj['name']

                if ('photos' in obj):
                    preprocessed['photos'] = obj['photos']
                preprocessed['types'] = obj['types']
                db.touristLocations.insert(preprocessed)
                print (name)

    else:
        print ("Could not find " + name)

